branch-defaults:
  default:
    environment: q4-butterfly
  master:
    environment: q4-butterfly
environment-defaults:
  q4-butterfly:
    branch: null
    repository: null
global:
  application_name: q4-butterfly-wordpress
  default_ec2_keyname: StagingOregon
  default_platform: PHP 5.3
  default_region: us-west-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
